server:
  port: 443
  ssl:
    key-alias: alias
    key-store-password: 0l4jants
    key-store-type: PKCS12
    key-store: classpath:lqcpw.shinrun.cn.pfx
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf-8&isSSL=false
    username: root
    password: root
